server:
  port: 9001
spring:

  ### DA DOVE PRENDIAMO LA CONFIGURAZIONE? ###

 config:
   import:
    - optional:configserver:http://localhost:8088
 profiles:
    active:
    - qa
 application:
    name: book-service
eureka:
  instance:
    prefer-ip-address: true
    
    ### DOVE SI TROVA IL DISCOVERY? ###
    
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka, http://localhost:8901/eureka